// <auto-generated />
using System;
using MemUp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemUp.Migrations
{
    [DbContext(typeof(MemUpDbContext))]
    [Migration("20210107233112_AddCourseWordRelationship")]
    partial class AddCourseWordRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("MemUp.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MemUp.Models.CourseWord", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("CourseWord");
                });

            modelBuilder.Entity("MemUp.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishVocab")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("JapaneseVocab")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("KanaVocab")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("MemUp.Models.CourseWord", b =>
                {
                    b.HasOne("MemUp.Models.Course", "Course")
                        .WithMany("CourseWords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemUp.Models.Word", "Word")
                        .WithMany("CourseWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
